### ISSUE TITLE
Tooltips in multiplayer not working correctly

### ISSUE THREAD

**Issue by AnimusOccisor** [McJtyMods/FancyTrinkets#5]
Made a mod pack, No fancy customized recipes, just plain mods. In single-player recipes can be viewed and hoovering over a crafted ring shows buffs and debufs on the tooltip

Multiplayer the recipes do not show (JEI shows the item but not how to craft them) and when crafting (that works) the buffs and debufs a ring would give are also not shown on the tooltip.

Even made sure no hidden configs got copied, both server and single-player created from the same curse client export (with only mods in the export), I'm lost 

fancytrinkets-1.19-2.1.1.jar and maybe related theoneprobe-1.19-6.2.2.jar

**Comment by McJty** [comment]
Hmm weird. What Minecraft version?

**Comment by AnimusOccisor** [comment]
Minecraft 1.19.2 
Forge 43.2.8 also tried Forge 43.2.7
and with jei-1.19.2-forge-11.6.0.1013.jar

Side note, previous version for fancy trinkets 1.19.2 also had that issue on the server. Had hopes it was solved with the update.

**Comment by McJty** [comment]
I'll check it out later

**Comment by McJty** [comment]
I managed to reproduce the problem. Now I can try to find out what's wrong

**Comment by McJty** [comment]
Fixed

**Comment by AnimusOccisor** [comment]
I'll check it out this weekend. Got a bunch of mod updates. So double backup before the update and check if nothing breaks.

Tnx for the quick fix in advance :)
